import test from "node:test";
import assert from "node:assert/strict";
import {
  renderReportSnapshotPdf,
  computeReportSnapshotHash,
  buildReportSnapshotPdfPackage,
  attachmentDisplayName,
  shortHash
} from "../src/lib/report-pdf.mjs";

function asText(buffer) {
  return Buffer.from(buffer).toString("latin1");
}

const SCHEMA = {
  sections: [
    {
      title: "Opening",
      fields: [
        { key: "supervisor", label: "Supervisor", type: "text", required: true },
        { key: "attendance", label: "Attendance", type: "number", required: true },
        { key: "secret_note", label: "Internal Note", type: "text", hidden: true }
      ]
    }
  ]
};

const GENERATED_AT = "2026-07-18T20:00:00.000Z";

const BASE_ARGS = {
  facilityName: "Riverside Rec Center",
  departmentName: "Aquatics",
  templateName: "Daily Pool Opening",
  templateCode: "pool_open",
  versionNumber: 3,
  reportDate: "2026-07-18",
  shiftRef: "AM",
  status: "submitted",
  schema: SCHEMA,
  payload: { supervisor: "Sam Submitter", attendance: 12, secret_note: "do not print this" },
  submitterName: "Sam Submitter",
  submittedAt: GENERATED_AT,
  revisionOf: null,
  attachments: [{ id: "att-1", storage_path: "facilities/fac-1/reports/sub-1/11111111-1111-1111-1111-111111111111-signage.jpg" }],
  signatures: [],
  generatedAt: GENERATED_AT,
  generatedBy: "system"
};

// --- PDF structure ------------------------------------------------------

test("renderReportSnapshotPdf emits a PDF 1.4 header and %%EOF trailer", () => {
  const text = asText(renderReportSnapshotPdf(BASE_ARGS));
  assert.ok(text.startsWith("%PDF-1.4\n"));
  assert.equal(text.trimEnd().endsWith("%%EOF"), true);
});

test("renderReportSnapshotPdf includes header metadata in schema order", () => {
  const text = asText(renderReportSnapshotPdf(BASE_ARGS));
  assert.match(text, /\(Facility: Riverside Rec Center\) Tj/);
  assert.match(text, /\(Department: Aquatics\) Tj/);
  assert.match(text, /\(Report Type: Daily Pool Opening\) Tj/);
  assert.match(text, /\(Template Code: pool_open\) Tj/);
  assert.match(text, /\(Template Version: 3\) Tj/);
  assert.match(text, /\(Report Date: 2026-07-18\) Tj/);
  assert.match(text, /\(Submitted By: Sam Submitter\) Tj/);
  assert.match(text, /\(Submitted At: 2026-07-18T20:00:00\.000Z\) Tj/);
  assert.match(text, /\(Revision Of: --\) Tj/);
});

test("renderReportSnapshotPdf includes every visible field label and value", () => {
  const text = asText(renderReportSnapshotPdf(BASE_ARGS));
  assert.match(text, /== Opening ==/);
  assert.match(text, /\(Supervisor: Sam Submitter\) Tj/);
  assert.match(text, /\(Attendance: 12\) Tj/);
});

test("renderReportSnapshotPdf omits fields marked hidden", () => {
  const text = asText(renderReportSnapshotPdf(BASE_ARGS));
  assert.doesNotMatch(text, /Internal Note/);
  assert.doesNotMatch(text, /do not print this/);
});

test("renderReportSnapshotPdf lists attachments by filename, stripping the uuid prefix", () => {
  const text = asText(renderReportSnapshotPdf(BASE_ARGS));
  assert.match(text, /== Attachments ==/);
  assert.match(text, /\(Attachment 1: signage\.jpg\) Tj/);
});

test("renderReportSnapshotPdf shows 'None recorded' for attachments when there are none", () => {
  const text = asText(renderReportSnapshotPdf({ ...BASE_ARGS, attachments: [] }));
  assert.match(text, /Attachments: None recorded/);
});

test("renderReportSnapshotPdf omits the Signatures section entirely when there are none", () => {
  const text = asText(renderReportSnapshotPdf(BASE_ARGS));
  assert.doesNotMatch(text, /== Signatures ==/);
});

test("renderReportSnapshotPdf lists signatures when provided", () => {
  const text = asText(
    renderReportSnapshotPdf({
      ...BASE_ARGS,
      signatures: [{ id: "sig-1", signer_name: "Pat Supervisor", role: "supervisor", signed_at: "2026-07-18T20:05:00Z" }]
    })
  );
  assert.match(text, /== Signatures ==/);
  assert.match(text, /\(Signature 1 Name: Pat Supervisor\) Tj/);
  assert.match(text, /\(Signature 1 Role: supervisor\) Tj/);
  assert.match(text, /\(Signature 1 Signed At: 2026-07-18T20:05:00Z\) Tj/);
});

test("renderReportSnapshotPdf tags a non-submitted status in the title", () => {
  const text = asText(renderReportSnapshotPdf({ ...BASE_ARGS, status: "locked" }));
  assert.match(text, /\(Daily Pool Opening Snapshot - 2026-07-18 \[LOCKED\]\) Tj/);
});

test("renderReportSnapshotPdf includes an Integrity block with the document hash and generated-at", () => {
  const text = asText(renderReportSnapshotPdf(BASE_ARGS));
  assert.match(text, /== Integrity ==/);
  assert.match(text, /\(Document Hash: sha256:[0-9a-f]{64}\) Tj/);
  assert.match(text, /\(Generated At: 2026-07-18T20:00:00\.000Z\) Tj/);
  assert.match(text, /\(Generated By: system\) Tj/);
});

// --- attachmentDisplayName / shortHash --------------------------------------

test("attachmentDisplayName strips the uuid- prefix off a buildAttachmentPath-shaped path", () => {
  assert.equal(
    attachmentDisplayName("facilities/fac-1/reports/sub-1/11111111-1111-1111-1111-111111111111-signage.jpg"),
    "signage.jpg"
  );
});

test("attachmentDisplayName falls back to the raw last segment when there is no uuid prefix", () => {
  assert.equal(attachmentDisplayName("some/odd/path/plainname.jpg"), "plainname.jpg");
});

test("attachmentDisplayName accepts a row object with storage_path", () => {
  assert.equal(
    attachmentDisplayName({ storage_path: "facilities/fac-1/reports/sub-1/22222222-2222-2222-2222-222222222222-photo.png" }),
    "photo.png"
  );
});

test("shortHash returns the first 8 hex characters", () => {
  assert.equal(shortHash("a".repeat(64)), "aaaaaaaa");
});

// --- computeReportSnapshotHash -----------------------------------------------

test("computeReportSnapshotHash is a deterministic function of its inputs", () => {
  const hashA = computeReportSnapshotHash(BASE_ARGS);
  const hashB = computeReportSnapshotHash(BASE_ARGS);
  assert.equal(hashA, hashB);
  assert.match(hashA, /^[0-9a-f]{64}$/);

  const hashDifferentGeneratedAt = computeReportSnapshotHash({ ...BASE_ARGS, generatedAt: "2026-07-19T00:00:00.000Z" });
  assert.notEqual(hashA, hashDifferentGeneratedAt);

  const hashDifferentPayload = computeReportSnapshotHash({
    ...BASE_ARGS,
    payload: { ...BASE_ARGS.payload, attendance: 99 }
  });
  assert.notEqual(hashA, hashDifferentPayload);
});

// --- Determinism: no Date.now()/new Date() of its own ------------------------
// renderReportSnapshotPdf takes every timestamp from its inputs, but it is
// built on top of admin/pdf.mjs's renderPdfDocument, which stamps its own
// "Generated at <now>" header line from the real clock. Freezing the global
// Date for the duration of the render (via node:test's mock timers) makes
// that line deterministic too, so the FULL byte output -- not just the
// fields this module controls -- is reproducible for a fixed fixture. Same
// pattern as test/incident-pdf.test.mjs's identical test.
test("renderReportSnapshotPdf produces byte-identical output for a fixed fixture with the clock frozen", (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: new Date("2026-09-01T00:00:00.000Z") });
  const first = renderReportSnapshotPdf(BASE_ARGS);
  const second = renderReportSnapshotPdf(BASE_ARGS);
  assert.deepEqual(first, second);
  assert.ok(Buffer.compare(first, second) === 0);
});

test("buildReportSnapshotPdfPackage produces a byte-identical body for a fixed fixture with the clock frozen", (t) => {
  t.mock.timers.enable({ apis: ["Date"], now: new Date("2026-09-01T00:00:00.000Z") });
  const first = buildReportSnapshotPdfPackage({ ...BASE_ARGS, submissionId: "sub-1" });
  const second = buildReportSnapshotPdfPackage({ ...BASE_ARGS, submissionId: "sub-1" });
  assert.equal(first.body, second.body);
  assert.equal(first.documentHash, second.documentHash);
  assert.equal(first.filename, second.filename);
  assert.equal(first.filename, `report-sub-1-${shortHash(first.documentHash)}.pdf`);
});

// Two renders of the same row at DIFFERENT real times are still
// byte-identical -- the actual DR-23 acceptance criterion, proved without
// freezing the clock at all, since renderReportSnapshotPdf takes its
// "generated at" from the row's own submitted_at, not wall-clock time. This
// only holds with the clock frozen for the underlying renderPdfDocument's
// own "Generated at <now>" line (see above); this test isolates the part
// THIS module is responsible for: the content stream never references
// Date.now() itself.
test("two renders of the same row never diverge in their content-bearing fields regardless of when they run", () => {
  const first = renderReportSnapshotPdf(BASE_ARGS);
  const second = renderReportSnapshotPdf(BASE_ARGS);
  const firstText = asText(first);
  const secondText = asText(second);
  const stripGeneratedAtHeader = (text) => text.replace(/Generated at [^)]*\)/g, "Generated at <now>)");
  assert.equal(stripGeneratedAtHeader(firstText), stripGeneratedAtHeader(secondText));
});
